apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: bg-demo-argo
resources:
  - deployment-green.yaml
  - deployment-blue.yaml
  - service-green.yaml
  - service-blue.yaml
  - service-bg.yaml
  - route-bg.yaml
  - route-weighted.yaml